// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ota.proto

package ota

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message of otaserver to otaDistributer
type Params struct {
	Size                 int64    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Md5                  string   `protobuf:"bytes,3,opt,name=md5,proto3" json:"md5,omitempty"`
	Sha256               string   `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Version              string   `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c328c8bae87cd24, []int{0}
}

func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Params) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Params) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

func (m *Params) GetSha256() string {
	if m != nil {
		return m.Sha256
	}
	return ""
}

func (m *Params) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type DistributeData struct {
	PKey                 string   `protobuf:"bytes,1,opt,name=pKey,proto3" json:"pKey,omitempty"`
	DName                string   `protobuf:"bytes,2,opt,name=dName,proto3" json:"dName,omitempty"`
	Params               *Params  `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistributeData) Reset()         { *m = DistributeData{} }
func (m *DistributeData) String() string { return proto.CompactTextString(m) }
func (*DistributeData) ProtoMessage()    {}
func (*DistributeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c328c8bae87cd24, []int{1}
}

func (m *DistributeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributeData.Unmarshal(m, b)
}
func (m *DistributeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributeData.Marshal(b, m, deterministic)
}
func (m *DistributeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributeData.Merge(m, src)
}
func (m *DistributeData) XXX_Size() int {
	return xxx_messageInfo_DistributeData.Size(m)
}
func (m *DistributeData) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributeData.DiscardUnknown(m)
}

var xxx_messageInfo_DistributeData proto.InternalMessageInfo

func (m *DistributeData) GetPKey() string {
	if m != nil {
		return m.PKey
	}
	return ""
}

func (m *DistributeData) GetDName() string {
	if m != nil {
		return m.DName
	}
	return ""
}

func (m *DistributeData) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

type UpgradeRequest struct {
	DistributeData       []*DistributeData `protobuf:"bytes,1,rep,name=distributeData,proto3" json:"distributeData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpgradeRequest) Reset()         { *m = UpgradeRequest{} }
func (m *UpgradeRequest) String() string { return proto.CompactTextString(m) }
func (*UpgradeRequest) ProtoMessage()    {}
func (*UpgradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c328c8bae87cd24, []int{2}
}

func (m *UpgradeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeRequest.Unmarshal(m, b)
}
func (m *UpgradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeRequest.Marshal(b, m, deterministic)
}
func (m *UpgradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeRequest.Merge(m, src)
}
func (m *UpgradeRequest) XXX_Size() int {
	return xxx_messageInfo_UpgradeRequest.Size(m)
}
func (m *UpgradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeRequest proto.InternalMessageInfo

func (m *UpgradeRequest) GetDistributeData() []*DistributeData {
	if m != nil {
		return m.DistributeData
	}
	return nil
}

// The response message of otaDistributer to otaserver
type UpgradeReply struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeReply) Reset()         { *m = UpgradeReply{} }
func (m *UpgradeReply) String() string { return proto.CompactTextString(m) }
func (*UpgradeReply) ProtoMessage()    {}
func (*UpgradeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c328c8bae87cd24, []int{3}
}

func (m *UpgradeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeReply.Unmarshal(m, b)
}
func (m *UpgradeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeReply.Marshal(b, m, deterministic)
}
func (m *UpgradeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeReply.Merge(m, src)
}
func (m *UpgradeReply) XXX_Size() int {
	return xxx_messageInfo_UpgradeReply.Size(m)
}
func (m *UpgradeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeReply proto.InternalMessageInfo

func (m *UpgradeReply) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpgradeReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Data struct {
	Identifer            string   `protobuf:"bytes,1,opt,name=identifer,proto3" json:"identifer,omitempty"`
	Params               *Params  `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c328c8bae87cd24, []int{4}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetIdentifer() string {
	if m != nil {
		return m.Identifer
	}
	return ""
}

func (m *Data) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

type PushDownRequest struct {
	Mid                  string   `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	PKey                 string   `protobuf:"bytes,3,opt,name=pKey,proto3" json:"pKey,omitempty"`
	DName                string   `protobuf:"bytes,4,opt,name=dName,proto3" json:"dName,omitempty"`
	Obj                  string   `protobuf:"bytes,5,opt,name=obj,proto3" json:"obj,omitempty"`
	Action               string   `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	Data                 *Data    `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushDownRequest) Reset()         { *m = PushDownRequest{} }
func (m *PushDownRequest) String() string { return proto.CompactTextString(m) }
func (*PushDownRequest) ProtoMessage()    {}
func (*PushDownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c328c8bae87cd24, []int{5}
}

func (m *PushDownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushDownRequest.Unmarshal(m, b)
}
func (m *PushDownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushDownRequest.Marshal(b, m, deterministic)
}
func (m *PushDownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushDownRequest.Merge(m, src)
}
func (m *PushDownRequest) XXX_Size() int {
	return xxx_messageInfo_PushDownRequest.Size(m)
}
func (m *PushDownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushDownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushDownRequest proto.InternalMessageInfo

func (m *PushDownRequest) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

func (m *PushDownRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PushDownRequest) GetPKey() string {
	if m != nil {
		return m.PKey
	}
	return ""
}

func (m *PushDownRequest) GetDName() string {
	if m != nil {
		return m.DName
	}
	return ""
}

func (m *PushDownRequest) GetObj() string {
	if m != nil {
		return m.Obj
	}
	return ""
}

func (m *PushDownRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *PushDownRequest) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type PushDownReply struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushDownReply) Reset()         { *m = PushDownReply{} }
func (m *PushDownReply) String() string { return proto.CompactTextString(m) }
func (*PushDownReply) ProtoMessage()    {}
func (*PushDownReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c328c8bae87cd24, []int{6}
}

func (m *PushDownReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushDownReply.Unmarshal(m, b)
}
func (m *PushDownReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushDownReply.Marshal(b, m, deterministic)
}
func (m *PushDownReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushDownReply.Merge(m, src)
}
func (m *PushDownReply) XXX_Size() int {
	return xxx_messageInfo_PushDownReply.Size(m)
}
func (m *PushDownReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PushDownReply.DiscardUnknown(m)
}

var xxx_messageInfo_PushDownReply proto.InternalMessageInfo

func (m *PushDownReply) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PushDownReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "ota.Params")
	proto.RegisterType((*DistributeData)(nil), "ota.DistributeData")
	proto.RegisterType((*UpgradeRequest)(nil), "ota.UpgradeRequest")
	proto.RegisterType((*UpgradeReply)(nil), "ota.UpgradeReply")
	proto.RegisterType((*Data)(nil), "ota.Data")
	proto.RegisterType((*PushDownRequest)(nil), "ota.PushDownRequest")
	proto.RegisterType((*PushDownReply)(nil), "ota.PushDownReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OTAClient is the client API for OTA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OTAClient interface {
	UpgradeDistribute(ctx context.Context, in *UpgradeRequest, opts ...grpc.CallOption) (*UpgradeReply, error)
}

type oTAClient struct {
	cc *grpc.ClientConn
}

func NewOTAClient(cc *grpc.ClientConn) OTAClient {
	return &oTAClient{cc}
}

func (c *oTAClient) UpgradeDistribute(ctx context.Context, in *UpgradeRequest, opts ...grpc.CallOption) (*UpgradeReply, error) {
	out := new(UpgradeReply)
	err := c.cc.Invoke(ctx, "/ota.OTA/UpgradeDistribute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OTAServer is the server API for OTA service.
type OTAServer interface {
	UpgradeDistribute(context.Context, *UpgradeRequest) (*UpgradeReply, error)
}

func RegisterOTAServer(s *grpc.Server, srv OTAServer) {
	s.RegisterService(&_OTA_serviceDesc, srv)
}

func _OTA_UpgradeDistribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTAServer).UpgradeDistribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ota.OTA/UpgradeDistribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTAServer).UpgradeDistribute(ctx, req.(*UpgradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OTA_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ota.OTA",
	HandlerType: (*OTAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpgradeDistribute",
			Handler:    _OTA_UpgradeDistribute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ota.proto",
}

// DistributePushDownClient is the client API for DistributePushDown service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DistributePushDownClient interface {
	PushDown(ctx context.Context, in *PushDownRequest, opts ...grpc.CallOption) (*PushDownReply, error)
}

type distributePushDownClient struct {
	cc *grpc.ClientConn
}

func NewDistributePushDownClient(cc *grpc.ClientConn) DistributePushDownClient {
	return &distributePushDownClient{cc}
}

func (c *distributePushDownClient) PushDown(ctx context.Context, in *PushDownRequest, opts ...grpc.CallOption) (*PushDownReply, error) {
	out := new(PushDownReply)
	err := c.cc.Invoke(ctx, "/ota.DistributePushDown/PushDown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DistributePushDownServer is the server API for DistributePushDown service.
type DistributePushDownServer interface {
	PushDown(context.Context, *PushDownRequest) (*PushDownReply, error)
}

func RegisterDistributePushDownServer(s *grpc.Server, srv DistributePushDownServer) {
	s.RegisterService(&_DistributePushDown_serviceDesc, srv)
}

func _DistributePushDown_PushDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushDownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributePushDownServer).PushDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ota.DistributePushDown/PushDown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributePushDownServer).PushDown(ctx, req.(*PushDownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DistributePushDown_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ota.DistributePushDown",
	HandlerType: (*DistributePushDownServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushDown",
			Handler:    _DistributePushDown_PushDown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ota.proto",
}

func init() { proto.RegisterFile("ota.proto", fileDescriptor_3c328c8bae87cd24) }

var fileDescriptor_3c328c8bae87cd24 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4f, 0x6f, 0xda, 0x40,
	0x10, 0xc5, 0x6b, 0xd6, 0x98, 0x7a, 0x68, 0x29, 0x6c, 0x51, 0x65, 0xa1, 0x56, 0x42, 0xee, 0x85,
	0x13, 0x07, 0x57, 0xa0, 0x56, 0x55, 0x0f, 0x95, 0x7c, 0x89, 0xf2, 0x0f, 0x59, 0xc9, 0x39, 0x5a,
	0xb2, 0x9b, 0xe0, 0x08, 0x63, 0x67, 0x77, 0x9d, 0x88, 0x7c, 0xaa, 0x7c, 0xc4, 0x68, 0xff, 0x18,
	0x63, 0x94, 0x1c, 0x72, 0x9b, 0x79, 0x66, 0x67, 0xe6, 0xfd, 0x9e, 0x00, 0x3f, 0x97, 0x64, 0x5a,
	0xf0, 0x5c, 0xe6, 0x18, 0xe5, 0x92, 0x84, 0x1c, 0xbc, 0x05, 0xe1, 0x24, 0x13, 0x18, 0x83, 0x2b,
	0xd2, 0x27, 0x16, 0x38, 0x63, 0x67, 0x82, 0x12, 0x5d, 0xe3, 0x3e, 0xa0, 0x92, 0xaf, 0x83, 0xd6,
	0xd8, 0x99, 0xf8, 0x89, 0x2a, 0x95, 0x92, 0xd1, 0x59, 0x80, 0x8c, 0x92, 0xd1, 0x19, 0xfe, 0x06,
	0x9e, 0x58, 0x91, 0x68, 0x36, 0x0f, 0x5c, 0x2d, 0xda, 0x0e, 0x07, 0xd0, 0x79, 0x60, 0x5c, 0xa4,
	0xf9, 0x26, 0x68, 0xeb, 0x0f, 0x55, 0x1b, 0x5e, 0x41, 0x2f, 0x4e, 0x85, 0xe4, 0xe9, 0xb2, 0x94,
	0x2c, 0x26, 0x92, 0xa8, 0xdd, 0xc5, 0x31, 0xdb, 0xea, 0xdd, 0x7e, 0xa2, 0x6b, 0x3c, 0x84, 0x36,
	0x3d, 0x23, 0x19, 0xb3, 0xdb, 0x4d, 0x83, 0x7f, 0x82, 0x57, 0xe8, 0x7b, 0xf5, 0x09, 0xdd, 0xa8,
	0x3b, 0x55, 0x86, 0x8c, 0x85, 0xc4, 0x7e, 0x0a, 0x4f, 0xa1, 0x77, 0x59, 0xdc, 0x72, 0x42, 0x59,
	0xc2, 0xee, 0x4b, 0x26, 0x24, 0xfe, 0x0b, 0x3d, 0xda, 0x58, 0x19, 0x38, 0x63, 0x34, 0xe9, 0x46,
	0x5f, 0xf5, 0xf3, 0xe6, 0x35, 0xc9, 0xc1, 0x4f, 0xc3, 0xdf, 0xf0, 0x69, 0x37, 0xae, 0x58, 0x6f,
	0xb5, 0x63, 0x49, 0x64, 0x29, 0x2c, 0x2b, 0xdb, 0x29, 0x36, 0x8c, 0xf3, 0x8a, 0x16, 0xe3, 0x3c,
	0x3c, 0x02, 0x57, 0xfb, 0xfb, 0x0e, 0x7e, 0x4a, 0xd9, 0x46, 0xa6, 0x37, 0x8c, 0x5b, 0x93, 0xb5,
	0xb0, 0xe7, 0xa9, 0xf5, 0xb6, 0xa7, 0x67, 0x07, 0xbe, 0x2c, 0x4a, 0xb1, 0x8a, 0xf3, 0xc7, 0x4d,
	0xe5, 0x4a, 0x85, 0x91, 0x52, 0x3b, 0x50, 0x95, 0xfb, 0xd0, 0x5b, 0x0d, 0xe8, 0x3b, 0xc4, 0xe8,
	0x35, 0xc4, 0xee, 0x3e, 0xe2, 0x3e, 0xa0, 0x7c, 0x79, 0x67, 0x43, 0x53, 0xa5, 0x32, 0x4c, 0xae,
	0xa5, 0x1a, 0xea, 0x99, 0x88, 0x4d, 0x87, 0x7f, 0x80, 0x4b, 0x15, 0xcb, 0x8e, 0x3e, 0xdb, 0x37,
	0x2c, 0x15, 0x41, 0x2d, 0x87, 0x7f, 0xe0, 0x73, 0x7d, 0xf1, 0xbb, 0xc0, 0x45, 0x31, 0xa0, 0xf3,
	0x8b, 0xff, 0xf8, 0x1f, 0x0c, 0x2c, 0xf9, 0x3a, 0x22, 0x6c, 0x32, 0x6b, 0x06, 0x3c, 0x1a, 0x34,
	0xc5, 0x62, 0xbd, 0x0d, 0x3f, 0x44, 0x27, 0x80, 0xeb, 0x77, 0xd5, 0x29, 0x78, 0x0e, 0x1f, 0x77,
	0xf5, 0xd0, 0xa0, 0x6e, 0x72, 0x1d, 0xe1, 0x03, 0x55, 0x4f, 0x5b, 0x7a, 0xfa, 0x6f, 0xf3, 0xeb,
	0x25, 0x00, 0x00, 0xff, 0xff, 0x37, 0x84, 0x3e, 0xcc, 0x43, 0x03, 0x00, 0x00,
}
